CREATE TABLE STUDENT(
ID integer not null,
NAME varchar(30) not null,
AGE integer not null,
GENDER ENUM('M','F') not null,
DOB DATE,
primary key(ID)
);

INSERT INTO STUDENT VALUES (1,'Niranjan',26,'M','2014-03-03');
INSERT INTO STUDENT VALUES (2,'Addanki',26,'M','2014-03-03');
INSERT INTO STUDENT VALUES (3,'Jake',26,'M','2014-03-03');
INSERT INTO STUDENT VALUES (4,'Johnson',26,'M','2014-03-03');
INSERT INTO STUDENT VALUES (5,'Shakti',20,'M','2014-08-03');



UPDATE STUDENT SET age = 21 WHERE name ='Shakti';

ALTER TABLE STUDENT DROP COLUMN AGE;

ALTER TABLE STUDENT ADD COLUMN AGE INT AFTER name;

ALTER TABLE STUDENT MODIFY COLUMN AGE not null;


# sorting values ascending order => null values are first

# first 2 values 
select * from STUDENT LIMIT 2;

# SKIP 2 , TAKE NEXT 2
SELECT * FROM STUDENT LIMIT 2,2;

#GET RANDOM VALUE
SELECT * FROM STUDENT ORDER BY RAND() LIMIT 1;

#ORDERING VALUES ASC -> DEFAULT , DESC -> DESCENDING , 
#NULL VALUES ARE FIRST IF VALUES ARE ORDERED IN ascending ORDER, LAST IF VALUES ARE ORDERED LAST FOR DESCENDING
SELECT * FROM STUDENT ORDER BY NAME ;

# DATE FORMAT 'YYYY-MM-DD'
# DAY(DATE) -> DD
# DAYOFWEEK(DATE) -> WEEKDAY MONDAY/...
# MONTH(DATE) -> MM
# YEAR(DATE) -> YYYY

SELECT CURDATE(), DAYOFWEEK(CURDATE());

# TIMESTAMP(YEAR,BDAY,CURDATE()) -> NUMBER OF YEARS
# TIMESTAMP(MONTH, BDAY, CURDATE()) -> NUMBER OF MONTHS
# TIMESTAMP(DAY, BDAY,CURDATE()) -> NUMBER OF YEARS


# DATE_ADD -> ADD MONTHS, YEARS,DAYS 
# DATE_SUB -> SUBTRACT MONTHS, YEAR, DAYS
SELECT DATE_ADD(CURDATE(),INTERVAL 1 MONTH);
SELECT DATE_SUB(CURDATE(),INTERVAL 1 DAY);
SELECT DATE_ADD(CURDATE(),INTERVAL 1 YEAR);

/*
# PATTERN MATCHING
% -> MATCHES ANY NUMBER OF CHARACTER
_ -> MATCHES ANY SINGLE CHARACTER
NAME LIKE '%N%' MATCHES N OR n 
NAME LIKE '____' MATCHES WORDS WITH LENGTH OF 4
*/
SELECT * FROM STUDENT WHERE NAME LIKE '%N%';
SELECT * FROM STUDENT WHERE NAME LIKE '___';

/* 
 MY SQL HAS ABLITY TO SAVE VARIABLES 
SELECT @NAME:=NAME FROM STUDENT WHERE NAME ='Niranjan';
SELECT * FROM STUDENT WHERE NAME=@name;
*/
SELECT @NAME:=NAME FROM STUDENT WHERE NAME ='Niranjan';
SELECT * FROM STUDENT WHERE NAME=@name;


/* 
DISTINCT -> RETURNS DISTINT NUMBER OF RECORDS
COUNT(*) -> RETURNS NUMBER OF RECORDS
COUNT(COLUMN) -> RETURNS NUMBER OF VALUES FOR A COLUMN , IGNORES NULL VALUES
*/
SELECT COUNT(*),COUNT(DISTINCT DOB),COUNT(AGE) FROM STUDENT ;

# GROUP BY WITH ROLLUP -> GIVES SUMMARY INFORMATION

SELECT NAME, COUNT(*) FROM STUDENT GROUP BY NAME WITH ROLLUP;

/*
INNER JOIN -> inner join 
OUTER JOIN -> OUTER JOIN
LEFT JOIN -> LEFT OUTER JOIN
RIGHT JOIN -> RIGHT OUTER JOIN
*/

/* 
DELETE FROM STUDENT WHERE NAME ='Niranjan';
*/


